### PR TITLE
Organize CorePPL to MExpr compiler and implement importance sampling

### PR DESCRIPTION
**Pull request by dlunde**
# Major changes
- Set up overall organization of CorePPL -> MExpr compiler.
- Add first inference algorithm (importance sampling) to CorePPL -> MExpr compiler.

# Minor changes
- Renamed `middpl` command to `cppl`
- Renamed `rootppl` command to `rppl` (for consistency with above)
- Removed `install-rootppl` and `uninstall-rootppl` (now part of `install` and `uninstall`)
- Move everything under `coreppl/` except `coreppl/models/` to `coreppl/src` (to mimic the structure in, e.g., `rootppl/`)
- Renamed `getAst` to the more descriptive `parseMCorePPLFile` and also make it allow free variables.
- Update `unify` arguments after https://github.com/miking-lang/miking/pull/581.
- Add `coreppl/src/src-location.mc` for determining the installed location of Miking DPPL on the current system.
- Remove `webppl/` folder after discussion with @vsenderov  and @david-broman.
- Update alignment analysis after https://github.com/miking-lang/miking/pull/583.

### CODE REVIEW

**Comment by david-broman** [comment]
Why `cppl`? If the other command is called `rootppl`, is it not clearer to call the RootPPL command `rootppl`?

**Comment by dlunde** [comment]
It's a command we (or, at least I) will use a lot, so I wanted to make it short just like we have `mi` instead of `miking` and as we had `midppl` instead of `miking-dppl`. Maybe we should rename `rootppl` to `rppl`?

**Comment by vsenderov** [comment]
I am not sure it makes sense to install both CorePPL and RootPPL together with one command. The reason is that CoreePPL obviously depends on miking, whereas RootPPL is a standalone application that depends on gcc and nvcc, essentially. I actually do have "machines", where I only have RootPPL running but not Miking/ CorePPL.

**Comment by vsenderov** [comment]
This also kind of fits with your idea @dlunde to have the TreePPL install separate as well. So in a nutshell, in my opinion, `make install` should only install CorePPL. And the various DSL's should be installed with their own commands, which actually may have different prerequisites.

**Pull request merged**
